services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: chaincacao
      POSTGRES_PASSWORD: chaincacao
      POSTGRES_DB: chaincacao
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chaincacao -d chaincacao"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://chaincacao:chaincacao@postgres:5432/chaincacao?sslmode=disable
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ../fabric-samples/test-network/organizations:/fabric-crypto:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 127.0.0.11
      - 192.168.1.254
      - 8.8.8.8
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
